---
title: "data_visualisation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data_visualisation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(npmlangevin)
set.seed(5105)
```

# Simulate field, track, and pings

```{r simulate}
sim<- simulate(
  nt = 500,
  nping = 30,
  boundary_sharpness = 1,
  boundary_limit = 0.9,
  pred_loc_delta = 0.5,
  ping_tau = 0.01 * c(1, 1),
  gamma = 0.1,
  cv_code = 1,
  cv_pars = c(0.4, 0.5, 1),
  loc_class_probs = c(
    G = 1,
    `3` = 0,
    `2` = 0,
    `1` = 0,
    `0` = 0,
    A = 0,
    B = 0
  )
)
```

```{r, fig.width=6}
with(sim$tmap, pred_field + track)

with(sim$tmap, pred_util + track)
```


# Investigate empirical gradients

```{r empirical-gradient}
track<- sim$track
track$x<- st_coordinates(track)[, "X"]
track$y<- st_coordinates(track)[, "Y"]
track$diff_x<- c(diff(track$x), NA)
track$diff_y<- c(diff(track$y), NA)

track$emp_dx<- with(
  track,
  {
    c(
      2 * diff(t)^(-1) * diff(x),
      NA
    )
  }
)
track$emp_dy<- with(
  track,
  {
    c(
      2 * diff(t)^(-1) * diff(y),
      NA
    )
  }
)
```

```{r}
cor(track[1:20, c("dx", "emp_dx", "emp_dy", "dy"), drop = TRUE], use = "complete.obs")

plot.ts(
  track[, c("dx", "diff_x"), drop = TRUE]
)

plot(
  track[, c("dx", "emp_dx"), drop = TRUE]
)
plot(
  track[, c("dy", "emp_dy"), drop = TRUE]
)
```