---
title: "nngp_simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{nngp_simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(npmlangevin)
```

```{r}
xlim<- c(-2, 2)
ylim<- c(-2, 2)
cv_code<- 1
cv_pars<- c(1, 0.25, 6.5)
boundary_sharpness<- 3

pred_locs<- st_as_sf(
  expand.grid(
    x = seq(min(xlim), max(xlim), by = 0.1),
    y = seq(min(ylim), max(ylim), by = 0.1),
    v = 1:3
  ),
  coords = c("x", "y")
)
# pred_locs<- st_as_sf(
#   expand.grid(
#     x = xlim,
#     y = ylim,
#     v = 1:3
#   ),
#   coords = c("x", "y")
# )

g<- make_nn_graph(
  x = xlim,
  y = ylim,
  cv_pars = cv_pars,
  cv_code = cv_code
)
pwg<- make_pred_graph(
  pred_locs,
  g
)


```

```{r}
obj<- MakeADFun(
  data = list(
    model = "nngp_model",
    cv_code = cv_code,
    g = list(
      st_get_dimension_values(g$stars, "x"),
      st_get_dimension_values(g$stars, "y"),
      lapply(lapply(g$graph,`[[`, 1), `+`, - 1),
      lapply(lapply(g$graph,`[[`, 2), `+`, - 1)
    ),
    y = g$stars$w,
    pwg = list(
      var = integer(0),
      coord = matrix(0, nrow = 0, ncol = 2),
      parents = list()
    )
  ),
  para = list(
    boundary_x = 0.9 * xlim,
    boundary_y = 0.9 * ylim,
    working_boundary_sharpness = log(boundary_sharpness),
    working_cv_pars = log(cv_pars),
    w = g$stars$w
  ),
  map = list(
    boundary_x = as.factor(c(NA, NA)),
    boundary_y = as.factor(c(NA, NA)),
    working_boundary_sharpness = as.factor(NA)
  ),
  random = "w",
  DLL = "npmlangevin_TMB"
)
sim<- obj$simulate()
g$stars$w<- sim$w

fitobj<- MakeADFun(
  data = list(
    model = "nngp_model",
    cv_code = cv_code,
    g = list(
      st_get_dimension_values(g$stars, "x"),
      st_get_dimension_values(g$stars, "x"),
      lapply(lapply(g$graph,`[[`, 1), `+`, -1),
      lapply(lapply(g$graph,`[[`, 2), `+`, -1)
    ),
    y = sim$y,
    pwg = list(
      var = integer(0),
      coord = matrix(0, nrow = 0, ncol = 2),
      parents = list()
    )
  ),
  para = list(
    boundary_x = 0.9 * xlim,
    boundary_y = 0.9 * ylim,
    working_boundary_sharpness = log(boundary_sharpness),
    working_cv_pars = log(cv_pars),
    w = 0 * g$stars$w
  ),
  map = list(
    boundary_x = as.factor(c(NA, NA)),
    boundary_y = as.factor(c(NA, NA)),
    working_boundary_sharpness = as.factor(NA),
    working_cv_pars = as.factor(c(1, 2, NA))
  ),
  random = "w",
  DLL = "npmlangevin_TMB"
)
opt_time<- system.time({
  opt<- nlminb(fitobj$par, fitobj$fn, fitobj$gr)
})
sdr<- sdreport(fitobj)

predobj<- MakeADFun(
  data = list(
    model = "nngp_model",
    cv_code = cv_code,
    g = list(
      st_get_dimension_values(g$stars, "x"),
      st_get_dimension_values(g$stars, "x"),
      lapply(lapply(g$graph,`[[`, 1), `+`, -1),
      lapply(lapply(g$graph,`[[`, 2), `+`, -1)
    ),
    y = sim$y,
    pwg = pred_graph_to_cpp(pwg)
  ),
  para = list(
    boundary_x = 0.9 * xlim,
    boundary_y = 0.9 * ylim,
    working_boundary_sharpness = log(boundary_sharpness),
    working_cv_pars = log(cv_pars),
    w = as.list(sdr, "Est")$w
  ),
  map = list(
    boundary_x = as.factor(c(NA, NA)),
    boundary_y = as.factor(c(NA, NA)),
    working_boundary_sharpness = as.factor(NA),
    working_cv_pars = as.factor(c(1, 2, NA))
  ),
  random = c("w"),
  DLL = "npmlangevin_TMB"
)
sdrpred<- sdreport(predobj, opt$par)
```

```{r}
pred<- st_sf(
  data.frame(
    w = as.list(sdrpred, "Est", report = TRUE)$pw,
    se = as.list(sdrpred, "Std", report = TRUE)$pw,
    pred_locs
  )
)
pred<- split(pred, pred$v)
pred<- lapply(
  pred,
  function(x) {
    x<- st_as_stars(x[c("w", "se")])
    x<- st_sfc2xy(x)
    return( x )
  }
)
pred<- do.call(c, c(pred, list(along = "v")))
st_dimensions(pred)$v$values<- c("gg", "dxdx", "dydy")
names(st_dimensions(pred))[1:2]<- c("x", "y")
attr(st_dimensions(pred), "raster")$dimensions<- c("x", "y")
```

```{r}
sim_rasters<- tm_shape(g$stars["w"]) +
  tm_raster(
    style = "cont",
    midpoint = 0,
    interpolate = FALSE,
    # palette = "viridis"
    palette = "PRGn"
  ) +
  tm_facets(nrow = 1, ncol = 3, free.scales = FALSE) +
  tm_layout(legend.outside = TRUE)

pred_rasters<- tm_shape(pred["w"]) +
  tm_raster(
    style = "cont",
    midpoint = 0,
    interpolate = FALSE,
    # palette = "viridis"
    palette = "PRGn"
  ) +
  tm_facets(nrow = 1, ncol = 3, free.scales = FALSE) +
  tm_layout(legend.outside = TRUE)

se_rasters<- tm_shape(pred["se"]) +
  tm_raster(
    style = "cont",
    interpolate = FALSE,
    palette = "viridis"
    # palette = "PRGn"
  ) +
  tm_facets(nrow = 1, ncol = 3, free.scales = FALSE) +
  tm_layout(legend.outside = TRUE)
```

```{r, fig.height = 10, fig.width = 8}
tmap_arrange(sim_rasters, pred_rasters, se_rasters, nrow = 3)
```